### ISSUE TITLE
Seria possivel disponibilizar a source do .exe?

### ISSUE THREAD

**Issue by aScriptingOreo** [ThallesLazaro/GunboundTH-Server-and-Game-Portable#1]
Opa, gostaria de saber como o .exe funciona por dentro para adapta-lo para shellscript e depois dockerfile, imagino que isso vá facilitar o deployment desse gameserver em qualquer sistema.

Consigo imaginar um pipeline simples de deployment na AWS/GCP/Azure se o projeto conter um dockerfile / compose.

**Comment by ThallesLazaro** [comment]
> Opa, gostaria de saber como o .exe funciona por dentro para adapta-lo para shellscript e depois dockerfile, imagino que isso vá facilitar o deployment desse gameserver em qualquer sistema.
> 
> Consigo imaginar um pipeline simples de deployment na AWS/GCP/Azure se o projeto conter um dockerfile / compose.

Como solicitado,  atualizei o repositório com os arquivos ".bat" originais, espero que ajude, ficaria feliz se compartilhasse alguma melhoria ou função se conseguir adicionar.

Abraços.

**Comment by aScriptingOreo** [comment]
Opa, valeu @ThallesLazaro! Dei uma olhada aqui e consegui desenrolar algumas coisas, outras vão ser mais dificeis. Pelo que entendi dos arquivos, uma das partes principais seria  "/Servidor/HTTP/bin/httpd_gb.exe", pelo que parece o apache roda direto do .exe ali.

Imagino que estes arquivos sejam referentes somente a pagina Web que disponibiliza o download(?) se for esse o caso a solução seria mais simples, um link de download em um host de terceiros no momento de criação da imagem Docker.

Podia me esclarecer se o "Script.py" é o "servidor" em si, e se possivel, quais portas de rede ele necessita? Se o "Servidor" for somente o Script.py, imagino que já consiga rodar como um container sem muitos problemas.

Valeu de novo :)
